<a href="https://colab.research.google.com/github/Phani170/Learning_Generative-AI/blob/main/Data%20Preprocessing%20and%20Embeddings/Text-Representation_Word%20Embeddings-1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Some common terms to remember:
1. Corpus
2. Vocabulary
3. Document
4. Word

# One Hot Encoding

In [57]:
import numpy as np
import pandas as pd

In [67]:
from sklearn.feature_extraction.text import CountVectorizer
df = pd.DataFrame({"text":["people watch dsa",
                         "dsa watch dsa",
                         "people write comment",
                          "dsa write comment"],"output":[1,1,0,0]})

In [68]:
# Initialize CountVectorizer with binary=True (one-hot style)
vectorizer = CountVectorizer(binary=True)

In [69]:
# Fit and transform the text column
X = vectorizer.fit_transform(df['text'])

In [70]:
# Convert to DataFrame
one_hot_df = pd.DataFrame(X.toarray(), columns=vectorizer.get_feature_names_out())

# Combine with the original 'output' column
final_df = pd.concat([df[['text', 'output']], one_hot_df], axis=1)

In [72]:
final_df

text  output  comment  dsa  people  watch  write
0      people watch dsa       1        0    1       1      1      0
1         dsa watch dsa       1        0    1       0      1      0
2  people write comment       0        1    0       1      0      1
3     dsa write comment       0        1    1       0      0      1

# Bag of words

In [35]:
df = pd.DataFrame({"text":["people watch dsa",
                         "dsa watch dsa",
                         "people write comment",
                          "dsa write comment"],"output":[1,1,0,0]})

df

text  output
0      people watch dsa       1
1         dsa watch dsa       1
2  people write comment       0
3     dsa write comment       0

In [36]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer() # Function for bag of words

In [37]:
bow = cv.fit_transform(df['text'])

In [38]:
#vocabulary
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'dsa': 1, 'write': 4, 'comment': 0}


In [39]:
bow.toarray()

array([[0, 1, 1, 1, 0],
       [0, 2, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [1, 1, 0, 0, 1]])

In [7]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[0 1 1 1 0]]
[[0 2 0 1 0]]
[[1 0 1 0 1]]


In [41]:
# new
cv.transform(['Phani watch dsa']).toarray()

array([[0, 1, 0, 1, 0]])

In [9]:
X = bow.toarray()
y = df['output']

#  N-grams

In [43]:
df = pd.DataFrame({"text":["people watch dsa",
                         "dsa watch dsa",
                         "people write comment",
                          "dsa write comment"],"output":[1,1,0,0]})

df

text  output
0      people watch dsa       1
1         dsa watch dsa       1
2  people write comment       0
3     dsa write comment       0

In [44]:
# BI grams
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(2,2))

In [46]:
bow = cv.fit_transform(df['text'])

In [47]:
print(cv.vocabulary_)

{'people watch': 2, 'watch dsa': 4, 'dsa watch': 0, 'people write': 3, 'write comment': 5, 'dsa write': 1}


In [14]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[0 0 1 0 1 0]]
[[1 0 0 0 1 0]]
[[0 0 0 1 0 1]]


In [48]:
#Ti gram
# BI grams
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(3,3))

In [49]:
bow = cv.fit_transform(df['text'])

In [50]:
print(cv.vocabulary_)

{'people watch dsa': 2, 'dsa watch dsa': 0, 'people write comment': 3, 'dsa write comment': 1}


In [51]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[0 0 1 0]]
[[1 0 0 0]]
[[0 0 0 1]]


# TF-IDF (Term frequency- Inverse document frequency)

In [52]:
df = pd.DataFrame({"text":["people watch dsa",
                         "dsa watch dsa",
                         "people write comment",
                          "dsa write comment"],"output":[1,1,0,0]})

df

text  output
0      people watch dsa       1
1         dsa watch dsa       1
2  people write comment       0
3     dsa write comment       0

In [53]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfid= TfidfVectorizer()

In [54]:
arr = tfid.fit_transform(df['text']).toarray()

In [55]:
arr

array([[0.        , 0.49681612, 0.61366674, 0.61366674, 0.        ],
       [0.        , 0.8508161 , 0.        , 0.52546357, 0.        ],
       [0.57735027, 0.        , 0.57735027, 0.        , 0.57735027],
       [0.61366674, 0.49681612, 0.        , 0.        , 0.61366674]])

In [56]:
print(tfid.idf_)

[1.51082562 1.22314355 1.51082562 1.51082562 1.51082562]
